apiVersion: apps/v1
kind: Deployment
metadata:
  name: PKL-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PKL-test
  template:
    metadata:
      labels:
        app: PKL-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: PKL-test
        image: containerrgtest1.azurecr.io/first_image:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: PKL-test
spec:
  ports:
  - port: 6379
  selector:
    app: PKL-test
